env:
- REPORT_CARD_GITHUB_STATUS_TOKEN=$$report_card_github_status_token
- REPORT_CARD_GITHUB_REPO_TOKEN=$$report_card_github_repo_token
image: python2.7
script:
- sudo pip install -q git+https://$REPORT_CARD_GITHUB_REPO_TOKEN@github.com/Clever/report-card.git; GITHUB_API_TOKEN=$REPORT_CARD_GITHUB_STATUS_TOKEN report-card --publish || true
- pip install -U pip
- make test
notify:
  email:
    recipients:
      - drone@clever.com
